# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/employee_leave_db
spring.datasource.username=root
spring.datasource.password=Hemanth@61
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=employee-leave-system